apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-crud-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: go-crud
  template:
    metadata:
      labels:
        app: go-crud
    spec:
      containers:
      - name: go-crud
        image: go-crud-k8s:latest # Update this to your image repository if using a remote one
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: go-crud-service
spec:
  type: LoadBalancer
  ports:
    - port: 8000
      targetPort: 8000
  selector:
    app: go-crud
